### ISSUE TITLE
`Workitem` should be `WorkItem` as per .NET naming conventions

### ISSUE THREAD

**Issue by ivanz** [javierholguera/vsoapiclient#1]
`Workitem` should be camel case `WorkItem` as per .NET naming conventions

**Comment by javierholguera** [comment]
You got it 😉


I'm so used to read it together that I thought it was one word…






Sent from Windows Mail





From: Ivan Zlatev
Sent: ‎Monday‎, ‎2‎ ‎February‎ ‎2015 ‎22‎:‎04
To: javierholguera/vsoapiclient





Workitem should be camel case WorkItem as per .NET naming conventions
